In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("C:\\Users\\hp\\Desktop\\Folders\\Training Internship\\Major_project\\amazon_alexa_data.csv")
df.head()

Unnamed: 0  rating       date         variation  \
0           0       5  31-Jul-18  Charcoal Fabric    
1           1       5  31-Jul-18  Charcoal Fabric    
2           2       4  31-Jul-18    Walnut Finish    
3           3       5  31-Jul-18  Charcoal Fabric    
4           4       5  31-Jul-18  Charcoal Fabric    

                                    verified_reviews  feedback  
0                                      Love my Echo!         1  
1                                          Loved it!         1  
2  Sometimes while playing a game, you can answer...         1  
3  I have had a lot of fun with this thing. My 4 ...         1  
4                                              Music         1

In [3]:
df.drop("Unnamed: 0", axis = 1)

rating       date         variation  \
0          5  31-Jul-18  Charcoal Fabric    
1          5  31-Jul-18  Charcoal Fabric    
2          4  31-Jul-18    Walnut Finish    
3          5  31-Jul-18  Charcoal Fabric    
4          5  31-Jul-18  Charcoal Fabric    
...      ...        ...               ...   
3145       5  30-Jul-18        Black  Dot   
3146       5  30-Jul-18        Black  Dot   
3147       5  30-Jul-18        Black  Dot   
3148       5  30-Jul-18        White  Dot   
3149       4  29-Jul-18        Black  Dot   

                                       verified_reviews  feedback  
0                                         Love my Echo!         1  
1                                             Loved it!         1  
2     Sometimes while playing a game, you can answer...         1  
3     I have had a lot of fun with this thing. My 4 ...         1  
4                                                 Music         1  
...                                                 ...       ...  
3145  Perfect for kids, adults and everyone in betwe...         1  
3146  Listening to music, searching locations, check...         1  
3147  I do love these things, i have them running my...         1  
3148  Only complaint I have is that the sound qualit...         1  
3149                                               Good         1  

[3150 rows x 5 columns]

## Checking for null values

In [4]:
df.isnull().sum()

Unnamed: 0          0
rating              0
date                0
variation           0
verified_reviews    0
feedback            0
dtype: int64

## Word pre-processing

In [5]:
from nltk import word_tokenize

In [6]:
data = df["verified_reviews"]
print(data)

0                                           Love my Echo!
1                                               Loved it!
2       Sometimes while playing a game, you can answer...
3       I have had a lot of fun with this thing. My 4 ...
4                                                   Music
                              ...                        
3145    Perfect for kids, adults and everyone in betwe...
3146    Listening to music, searching locations, check...
3147    I do love these things, i have them running my...
3148    Only complaint I have is that the sound qualit...
3149                                                 Good
Name: verified_reviews, Length: 3150, dtype: object


In [7]:
from nltk.corpus import stopwords
sw = stopwords.words('english')
print(sw)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [8]:
import re

In [9]:
from nltk.stem import WordNetLemmatizer
lm = WordNetLemmatizer()
msg = []
for i in data:
    t = re.sub('[^A-Za-z0-9]', ' ', i)       # Removing Punctuations
    t = t.lower()                            # Turning all to lower case
    t = word_tokenize(t)                     # Word tokenization
    t = [i for i in t if t not in sw]        # Removing stopwords
    t = [lm.lemmatize(i) for i in t]         # Lemmatization
    t = " ".join(t)
    msg.append(t)
print(msg)

['love my echo', 'loved it', 'sometimes while playing a game you can answer a question correctly but alexa say you got it wrong and answer the same a you i like being able to turn light on and off while away from home', 'i have had a lot of fun with this thing my 4 yr old learns about dinosaur i control the light and play game like category ha nice sound when playing music a well', 'music', 'i received the echo a a gift i needed another bluetooth or something to play music easily accessible and found this smart speaker can t wait to see what else it can do', 'without having a cellphone i can not use many of her feature i have an ipad but do not see that of any use it is a great alarm if u r almost deaf you can hear her alarm in the bedroom from out in the living room so that is reason enough to keep her it is fun to ask random question to hear her response she doe not seem to be very smartbon politics yet', 'i think this is the 5th one i ve purchased i m working on getting one in every

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
cv = CountVectorizer()
cv_res = cv.fit_transform(msg).toarray()
print(cv_res)
print(cv.get_feature_names())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['00', '000', '07', '10', '100', '100x', '11', '1100sf', '12', '129', '12am', '15', '150', '18', '19', '1964', '1990', '1gb', '1rst', '1st', '20', '200', '2000', '2017', '229', '23', '24', '25', '29', '2nd', '2package', '30', '300', '30pm', '34', '360', '39', '3rd', '3x', '3xs', '40', '45', '48', '4am', '4ghz', '4k', '4th', '50', '54', '5am', '5ghz', '5th', '600', '62', '672', '6th', '70', '75', '79', '80', '81', '83', '85', '88', '888', '8gb', '90', '91', '911', '99', 'a1', 'a19', 'abay', 'abc', 'abd', 'ability', 'able', 'abode', 'about', 'above', 'absolutely', 'absolutly', 'ac', 'accent', 'acceptable', 'accepting', 'access', 'accessable', 'accessible', 'accessing', 'accessory', 'accident', 'accidentally', 'accompanying', 'accomplish', 'accomplished', 'according', 'accordingly', 'account', 'accuracy', 'accurate', 'accurately', 'accustom', 'acknowledge', 'acoustical',

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
y = df["feedback"]
x_train, x_test, y_train, y_test = train_test_split(cv_res, y, test_size = 0.25, random_state = 42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(2362, 3679)
(788, 3679)
(2362,)
(788,)


## KNN Model

In [14]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
m1 = KNeighborsClassifier()
m1.fit(x_train, y_train)

KNeighborsClassifier()

In [16]:
y_pred = m1.predict(x_test)

In [17]:
from sklearn.metrics import confusion_matrix, classification_report

In [18]:
def eval_model(ypred, ytest):
    cm = confusion_matrix(ytest, ypred)
    print(cm)
    print(classification_report(ytest, ypred))

def mscore(model):
    print("Training Score", model.score(x_train, y_train))
    print("Testing Score", model.score(x_test, y_test))

In [19]:
eval_model(y_pred, y_test)

[[  8  65]
 [ 20 695]]
              precision    recall  f1-score   support

           0       0.29      0.11      0.16        73
           1       0.91      0.97      0.94       715

    accuracy                           0.89       788
   macro avg       0.60      0.54      0.55       788
weighted avg       0.86      0.89      0.87       788



In [20]:
mscore(m1)

Training Score 0.9081287044877223
Testing Score 0.8921319796954315


## Logistic Regression

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
lr = LogisticRegression()
lr.fit(x_train, y_train)

LogisticRegression()

In [23]:
ypred1 = lr.predict(x_test)

In [24]:
eval_model(ypred1, y_test)

[[ 33  40]
 [  6 709]]
              precision    recall  f1-score   support

           0       0.85      0.45      0.59        73
           1       0.95      0.99      0.97       715

    accuracy                           0.94       788
   macro avg       0.90      0.72      0.78       788
weighted avg       0.94      0.94      0.93       788



In [25]:
mscore(lr)

Training Score 0.9813717188823031
Testing Score 0.9416243654822335


## Multinomial Naive Bayes

In [26]:
from sklearn.naive_bayes import MultinomialNB

In [27]:
mnb = MultinomialNB()
mnb.fit(x_train, y_train)

MultinomialNB()

In [28]:
ypred2 = mnb.predict(x_test)

In [29]:
eval_model(ypred2, y_test)

[[ 19  54]
 [  6 709]]
              precision    recall  f1-score   support

           0       0.76      0.26      0.39        73
           1       0.93      0.99      0.96       715

    accuracy                           0.92       788
   macro avg       0.84      0.63      0.67       788
weighted avg       0.91      0.92      0.91       788



In [30]:
mscore(mnb)

Training Score 0.9589331075359865
Testing Score 0.9238578680203046


## Conclusion

#### Logistic regression is the model with the best accuracy as the score of that model is the highest among the three machine learning model computed.