### Importing relevant libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("C:\\Users\\hp\\Desktop\\Folders\\Training Internship\\Minor_Project\\mobile_price_range_data.csv")
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

### Checking the data for null and duplicate values

In [3]:
print(df.isnull().sum())

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64


In [4]:
df.duplicated().sum()

0

### Splitting the data into test and train data

In [5]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.25)

In [8]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1500, 20)
(500, 20)
(1500,)
(500,)


### Logistic Regression

In [9]:
# As Logistic Regression is only done on categorical data hence the columns are narrowed down to only columns containing categorical data.
x_train1 = x_train[["blue", "dual_sim", "four_g", "three_g", "touch_screen", "wifi"]]
x_test1 = x_test[["blue", "dual_sim", "four_g", "three_g", "touch_screen", "wifi"]]

print(x_train1.head())
type(x_train1)
type(y_train)

      blue  dual_sim  four_g  three_g  touch_screen  wifi
1322     0         0       0        0             1     0
623      1         1       1        1             0     1
925      1         0       1        1             0     0
917      0         0       1        1             0     0
1976     1         0       0        1             1     1


pandas.core.series.Series

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
m = LogisticRegression()
m.fit(x_train1, y_train)

LogisticRegression()

In [12]:
print("Training Score: ",m.score(x_train1, y_train))
print("Testing Score: ",m.score(x_test1, y_test))

Training Score:  0.272
Testing Score:  0.244


###### The score of the logistic regression 0.28 for train data and 0.23 for test data which shows that the accuracy of the logistic regression is not desirable

### KNN

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
df['price_range'].unique()

array([1, 2, 3, 0], dtype=int64)

In [15]:
m1 = KNeighborsClassifier(n_neighbors = 4)
m1.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [16]:
print("Training Score:", m1.score(x_train, y_train))
print("Testing Score:", m1.score(x_test, y_test))

Training Score: 0.948
Testing Score: 0.908


In [17]:
from sklearn.metrics import confusion_matrix, classification_report

In [18]:
def eval_model(ytrain, ypred):
    cm = confusion_matrix(ytrain, ypred)
    print(cm)
    print(classification_report(ytrain, ypred))

In [19]:
y_pred = m1.predict(x_test)

In [20]:
eval_model(y_test, y_pred)

[[116   5   0   0]
 [  5 110   1   0]
 [  0  15 118   7]
 [  0   0  13 110]]
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       121
           1       0.85      0.95      0.89       116
           2       0.89      0.84      0.87       140
           3       0.94      0.89      0.92       123

    accuracy                           0.91       500
   macro avg       0.91      0.91      0.91       500
weighted avg       0.91      0.91      0.91       500



In [21]:
print("Training Score", m1.score(x_train, y_train))
print("Testing Score", m1.score(x_test, y_test))

Training Score 0.948
Testing Score 0.908


## Decision Tree Classification

In [22]:
from sklearn.tree import DecisionTreeClassifier

In [23]:
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [24]:
dtc_pred = dtc.predict(x_test)

In [25]:
eval_model(y_test, dtc_pred)

[[108  12   1   0]
 [ 10  93  13   0]
 [  0  19 104  17]
 [  0   0  14 109]]
              precision    recall  f1-score   support

           0       0.92      0.89      0.90       121
           1       0.75      0.80      0.77       116
           2       0.79      0.74      0.76       140
           3       0.87      0.89      0.88       123

    accuracy                           0.83       500
   macro avg       0.83      0.83      0.83       500
weighted avg       0.83      0.83      0.83       500



In [26]:
print("Training Score", dtc.score(x_train, y_train))
print("Testing Score", dtc.score(x_test, y_test))

Training Score 1.0
Testing Score 0.828


## Random Forest Classification

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
rfc = RandomForestClassifier()
rfc.fit(x_train, y_train)

RandomForestClassifier()

In [29]:
rfc_pred = rfc.predict(x_test)

In [30]:
eval_model(y_test, rfc_pred)

[[115   6   0   0]
 [  6  97  13   0]
 [  0  15 110  15]
 [  0   0   8 115]]
              precision    recall  f1-score   support

           0       0.95      0.95      0.95       121
           1       0.82      0.84      0.83       116
           2       0.84      0.79      0.81       140
           3       0.88      0.93      0.91       123

    accuracy                           0.87       500
   macro avg       0.87      0.88      0.88       500
weighted avg       0.87      0.87      0.87       500



In [31]:
print("Training Score: ", rfc.score(x_train, y_train))
print("Testing Score: ", rfc.score(x_test, y_test))

Training Score:  1.0
Testing Score:  0.874


### SVM Classifier

In [32]:
from sklearn.svm import SVC

In [33]:
m2 = SVC(kernel = 'linear', C = 1)
m2.fit(x_train, y_train)

SVC(C=1, kernel='linear')

In [34]:
print("Training Score: ", m2.score(x_train, y_train))
print("Testing Score: ", m2.score(x_test, y_test))

Training Score:  0.994
Testing Score:  0.968


In [35]:
y_pred = m2.predict(x_test)

In [36]:
eval_model(y_test, y_pred)

[[121   0   0   0]
 [  3 111   2   0]
 [  0   3 131   6]
 [  0   0   2 121]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       121
           1       0.97      0.96      0.97       116
           2       0.97      0.94      0.95       140
           3       0.95      0.98      0.97       123

    accuracy                           0.97       500
   macro avg       0.97      0.97      0.97       500
weighted avg       0.97      0.97      0.97       500



#### SVM Classifier is the model with best accuracy as the testing score of this model is the heighest.